services:
  db:
    image: mysql:8.0.27
    container_name: db-container
    environment:
      MYSQL_ROOT_PASSWORD: KlikA2C123!
      MYSQL_DATABASE: KlikA2C
      MYSQL_USER: KlikA2C
      MYSQL_PASSWORD: KlikA2C123!
    healthcheck:
      test: ["CMD", "mysql", "-u", "KlikA2C", "-pKlikA2C123!", "-e", "show databases"]
      interval: 10s
    ports:
    - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  app:
    container_name: go-app
    build: .
    restart: always
    environment:
      CONN_STRING: KlikA2C:KlikA2C123!@tcp(db-container)/KlikA2C?charset=utf8&parseTime=True&loc=Local
    ports:
     - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  adminer:
    image: adminer
    restart: always
    ports: # host:container
      - 8081:8080
    depends_on:
      db:
        condition: service_healthy
        
volumes:
  dbdata: